# Generated by Django 3.2.9 on 2021-11-24 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_is_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_liked',
        ),
    ]
