# Generated by Django 3.2.9 on 2021-11-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20211120_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='movie_poster',
            new_name='poster_path',
        ),
    ]
