# Generated by Django 3.2.9 on 2021-11-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_movie_poster_like_poster_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='poster_path',
            new_name='like_poster_path',
        ),
    ]
