# Generated by Django 3.2.9 on 2021-11-22 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20211121_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawledmovie',
            old_name='gnere_3',
            new_name='genre_3',
        ),
    ]
