# Generated by Django 3.2.9 on 2021-11-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_rename_gnere_3_crawledmovie_genre_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawledmovie',
            name='movie_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
