# Generated by Django 3.2.9 on 2021-11-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reason',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(null=True),
        ),
    ]
